# Analysing baseball stats: Making predictions using linear and logistic regression

In [7]:
# Import libraries
import pandas as pd
import numpy as np
from sklearn import linear_model
from scipy import stats
import matplotlib.pyplot as plt
%matplotlib inline

## Step 1: Data Preprocessing
Using game logs from 2016 MLB season as sample input to build a sequence of methods, which can be later used to process game logs from multiple seasons to construct our training and test sets.

In [10]:
# read game logs taken from retrosheet into a pandas dataframe 

input_df = pd.read_table("game_data/GL2016.TXT", sep=",", header=None)

The dataset is unlablled.
So, we label the columns of interest to make it readable.
This [web page](http://www.retrosheet.org/gamelogs/glfields.txt) on retrosheet provides detail of what each column represents.

In [12]:
# method to label columns
def label_cols(input_df):
    input_df.rename(columns = {3: 'Visiting Team', 6: 'Home Team', 9: 'Visitor Score', 10: 'Home Score'}, inplace=True)
    return input_df

# call the function to label columns of interest
input_df = label_cols(input_df)

# use the head function to look the first few rows of the dataframe
input_df.head()

,0,1,2,Visiting Team,4,5,Home Team,7,8,Visitor Score,...,151,152,153,154,155,156,157,158,159,160
0,20160403,0,Sun,NYN,NL,1,KCA,AL,1,3,...,Salvador Perez,2,infao001,Omar Infante,4,fuenr001,Reymond Fuentes,9,NaN,Y
1,20160403,0,Sun,TOR,AL,1,TBA,AL,1,5,...,Steven Souza,9,kierk001,Kevin Kiermaier,8,congh001,Hank Conger,2,NaN,Y
2,20160403,0,Sun,SLN,NL,1,PIT,NL,1,1,...,Josh Harrison,4,mercj002,Jordy Mercer,6,lirif001,Francisco Liriano,1,NaN,Y
3,20160404,0,Mon,CHN,NL,1,ANA,AL,1,9,...,Andrelton Simmons,6,perec003,Carlos Perez,2,giavj001,Johnny Giavotella,4,NaN,Y
4,20160404,0,Mon,MIN,AL,1,BAL,AL,1,2,...,J.J. Hardy,6,schoj001,Jonathan Schoop,4,rickj001,Joey Rickard,7,NaN,Y